### ISSUE TITLE
Fix eventstore and eventsourced dependencies in mix.exs

### ISSUE THREAD

**Issue by andrzejsliwa** [slashdotdash/commanded#4]
Hi @slashdotdash,

really interesting project, I already trying to apply it, for some tests on my existing project 

I found some issues, for example problem when I fetch dependencies via hex.pm
looks like you didn't bumped up version, but you made already some changes (fixes)

I switched from hex to github and now its working. 
Would be good to wire commanded, eventsourced and eventsource via version on hex, instead of github, but probably its to early for it.

I will send you soon some feedback about using it on my project, I would love to discuss validations topics.

Next thing is handling commands with ack, in my case I have splited CQRS on http level:

```
POST /command
GET /query
WS /updates

```
I'm thinking also about adding:

`GET /command`

then we could handle commands as: fire & forget or fire & wait for ack.
This will require probably passing PID of web process to command handler, just idea.

If you are interested in feedback and discussion we can make skype call

**Comment by slashdotdash** [comment]
@andrzejsliwa Glad to hear that you're finding it useful. The `mix.exs` file is currently referencing the GitHub versions of `eventstore` and `eventsourced`. That needs to be changed to use the published versions on hex.pm. I'll make that change.  

For the application I'm building that uses commanded, I'm uses local references so that I can build features and fix issues as needed. These libs are all still young and under heavy development. They're all still 0.x versions.

Please do send me feedback, feature requests and ideas. I'm looking to add tasks to the [development roadmap](https://github.com/slashdotdash/commanded/projects/1). Email me at ben[at]10consulting.com if you want to discuss outside of GitHub.

**Comment by slashdotdash** [comment]
Fixed by commit a0f1797. Use hex for `eventstore` and `eventsourced` packages.
