### ISSUE TITLE
Application Examples inside the main folder

### ISSUE THREAD

**Issue by henry-hz** [slashdotdash/commanded#41]
Create an "examples" folder inside the Command root folder,  like the [ecto](https://github.com/elixir-ecto/ecto/tree/master/examples/friends) application, with two examples, the bank account and the conference reservation system (from Microsoft book).

**Comment by patrickdet** [comment]
having some examples would be gold

**Comment by slashdotdash** [comment]
@patrickdet There are some examples of aggregate roots, process manager, and command handlers in the [test/example_domain](https://github.com/slashdotdash/commanded/tree/master/test/example_domain) folder.

**Comment by brendanzab** [comment]
A full end-to-end example in a repo, like that described in [your blog post](https://10consulting.com/2017/01/04/building-a-cqrs-web-application-in-elixir-using-phoenix) would be super useful for understanding how everything fits together! I looked at the example domain, but it doesn't have all the wiring which is super handy to see when evaluating the library.

**Comment by drozzy** [comment]
For example to be truly effective, it should be a separate app. However, making a full app requires a lot of extra junk (e.g. dependencies, mix config etc.).

I think it should go into a separate repo - not be showed into the core. I suggest closing this issue, and if someone wants to create a pull request with examples, then do it.
Otherwise, I think this will never be done.

**Comment by slashdotdash** [comment]
@drozzy I've built an example application using Commanded that can probably suffice to resolve this issue. It's a Phoenix 1.3 web app called [Conduit](https://github.com/slashdotdash/conduit).

I will add a link to the README to direct users there if they wish to see an example implementation.
